name: smart_splash_kit_example
description: "Demonstrates how to use the smart_splash_kit plugin with all 5 templates."
publish_to: 'none'

environment:
  sdk: ^3.0.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  smart_splash_kit:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
